# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add_student.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_add_student(object):
    def setupUi(self, add_student):
        add_student.setObjectName(_fromUtf8("add_student"))
        add_student.resize(698, 518)
        self.formLayoutWidget = QtGui.QWidget(add_student)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 681, 501))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.NameLabel = QtGui.QLabel(self.formLayoutWidget)
        self.NameLabel.setObjectName(_fromUtf8("NameLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.NameLabel)
        self.nameLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nameLineEdit)
        self.DOBLabel = QtGui.QLabel(self.formLayoutWidget)
        self.DOBLabel.setObjectName(_fromUtf8("DOBLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.DOBLabel)
        self.DOBDateEdit = QtGui.QDateEdit(self.formLayoutWidget)
        self.DOBDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(1970, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DOBDateEdit.setObjectName(_fromUtf8("DOBDateEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.DOBDateEdit)
        self.homePhoneLabel = QtGui.QLabel(self.formLayoutWidget)
        self.homePhoneLabel.setObjectName(_fromUtf8("homePhoneLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.homePhoneLabel)
        self.homePhoneLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.homePhoneLineEdit.setObjectName(_fromUtf8("homePhoneLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.homePhoneLineEdit)
        self.cellPhoneLabel = QtGui.QLabel(self.formLayoutWidget)
        self.cellPhoneLabel.setObjectName(_fromUtf8("cellPhoneLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.cellPhoneLabel)
        self.cellPhoneLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.cellPhoneLineEdit.setObjectName(_fromUtf8("cellPhoneLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cellPhoneLineEdit)
        self.emergencyPhoneLabel = QtGui.QLabel(self.formLayoutWidget)
        self.emergencyPhoneLabel.setObjectName(_fromUtf8("emergencyPhoneLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.emergencyPhoneLabel)
        self.ePhoneLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.ePhoneLineEdit.setObjectName(_fromUtf8("ePhoneLineEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.ePhoneLineEdit)
        self.addressLabel = QtGui.QLabel(self.formLayoutWidget)
        self.addressLabel.setObjectName(_fromUtf8("addressLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.addressLabel)
        self.addressLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.addressLineEdit.setObjectName(_fromUtf8("addressLineEdit"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.addressLineEdit)
        self.cityLabel = QtGui.QLabel(self.formLayoutWidget)
        self.cityLabel.setObjectName(_fromUtf8("cityLabel"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.cityLabel)
        self.cityLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.cityLineEdit.setObjectName(_fromUtf8("cityLineEdit"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.cityLineEdit)
        self.stateLabel = QtGui.QLabel(self.formLayoutWidget)
        self.stateLabel.setObjectName(_fromUtf8("stateLabel"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.stateLabel)
        self.stateComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.stateComboBox.setObjectName(_fromUtf8("stateComboBox"))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.stateComboBox)
        self.zipcodeLabel = QtGui.QLabel(self.formLayoutWidget)
        self.zipcodeLabel.setObjectName(_fromUtf8("zipcodeLabel"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.zipcodeLabel)
        self.zipcodeLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.zipcodeLineEdit.setObjectName(_fromUtf8("zipcodeLineEdit"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.zipcodeLineEdit)
        self.emailLabel = QtGui.QLabel(self.formLayoutWidget)
        self.emailLabel.setObjectName(_fromUtf8("emailLabel"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.emailLabel)
        self.emailLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.emailLineEdit.setObjectName(_fromUtf8("emailLineEdit"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.emailLineEdit)
        self.genderLabel = QtGui.QLabel(self.formLayoutWidget)
        self.genderLabel.setObjectName(_fromUtf8("genderLabel"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.genderLabel)
        self.genderComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.genderComboBox.setObjectName(_fromUtf8("genderComboBox"))
        self.genderComboBox.addItem(_fromUtf8(""))
        self.genderComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.genderComboBox)
        self.primaryLabel = QtGui.QLabel(self.formLayoutWidget)
        self.primaryLabel.setObjectName(_fromUtf8("primaryLabel"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.primaryLabel)
        self.primaryComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.primaryComboBox.setObjectName(_fromUtf8("primaryComboBox"))
        self.primaryComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.primaryComboBox)
        self.secondaryLabel = QtGui.QLabel(self.formLayoutWidget)
        self.secondaryLabel.setObjectName(_fromUtf8("secondaryLabel"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.secondaryLabel)
        self.secondaryComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.secondaryComboBox.setObjectName(_fromUtf8("secondaryComboBox"))
        self.secondaryComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.secondaryComboBox)
        self.medicalLabel = QtGui.QLabel(self.formLayoutWidget)
        self.medicalLabel.setObjectName(_fromUtf8("medicalLabel"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.medicalLabel)
        self.requiredLabel = QtGui.QLabel(self.formLayoutWidget)
        self.requiredLabel.setObjectName(_fromUtf8("requiredLabel"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.LabelRole, self.requiredLabel)
        self.Submit_btn = QtGui.QPushButton(self.formLayoutWidget)
        self.Submit_btn.setObjectName(_fromUtf8("Submit_btn"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.Submit_btn)
        self.medicalTextEdit = QtGui.QTextEdit(self.formLayoutWidget)
        self.medicalTextEdit.setObjectName(_fromUtf8("medicalTextEdit"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.medicalTextEdit)
        self.eContact = QtGui.QLabel(self.formLayoutWidget)
        self.eContact.setObjectName(_fromUtf8("eContact"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.eContact)
        self.emergencyLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.emergencyLineEdit.setObjectName(_fromUtf8("emergencyLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.emergencyLineEdit)

        self.retranslateUi(add_student)
        QtCore.QMetaObject.connectSlotsByName(add_student)

    def retranslateUi(self, add_student):
        add_student.setWindowTitle(_translate("add_student", "Add Student", None))
        self.NameLabel.setText(_translate("add_student", "Name*", None))
        self.DOBLabel.setText(_translate("add_student", "Date of Birth*", None))
        self.homePhoneLabel.setText(_translate("add_student", "Home Phone*", None))
        self.cellPhoneLabel.setText(_translate("add_student", "Cell Phone", None))
        self.emergencyPhoneLabel.setText(_translate("add_student", "Emergency Phone", None))
        self.addressLabel.setText(_translate("add_student", "Address*", None))
        self.cityLabel.setText(_translate("add_student", "City*", None))
        self.stateLabel.setText(_translate("add_student", "State*", None))
        self.stateComboBox.setItemText(0, _translate("add_student", "Alabama", None))
        self.stateComboBox.setItemText(1, _translate("add_student", "Alaska", None))
        self.stateComboBox.setItemText(2, _translate("add_student", "Arizona", None))
        self.stateComboBox.setItemText(3, _translate("add_student", "Arkansas", None))
        self.stateComboBox.setItemText(4, _translate("add_student", "California", None))
        self.stateComboBox.setItemText(5, _translate("add_student", "Colorado", None))
        self.stateComboBox.setItemText(6, _translate("add_student", "Connecticut", None))
        self.stateComboBox.setItemText(7, _translate("add_student", "Delaware", None))
        self.stateComboBox.setItemText(8, _translate("add_student", "Florida", None))
        self.stateComboBox.setItemText(9, _translate("add_student", "Georgia", None))
        self.stateComboBox.setItemText(10, _translate("add_student", "Hawaii", None))
        self.stateComboBox.setItemText(11, _translate("add_student", "Idaho", None))
        self.stateComboBox.setItemText(12, _translate("add_student", "Illinois", None))
        self.stateComboBox.setItemText(13, _translate("add_student", "Indiana", None))
        self.stateComboBox.setItemText(14, _translate("add_student", "Iowa", None))
        self.stateComboBox.setItemText(15, _translate("add_student", "Kansas", None))
        self.stateComboBox.setItemText(16, _translate("add_student", "Kentucky", None))
        self.stateComboBox.setItemText(17, _translate("add_student", "Louisiana", None))
        self.stateComboBox.setItemText(18, _translate("add_student", "Maine", None))
        self.stateComboBox.setItemText(19, _translate("add_student", "Maryland", None))
        self.stateComboBox.setItemText(20, _translate("add_student", "Massachusetts", None))
        self.stateComboBox.setItemText(21, _translate("add_student", "Michigan", None))
        self.stateComboBox.setItemText(22, _translate("add_student", "Minnesota", None))
        self.stateComboBox.setItemText(23, _translate("add_student", "Mississippi", None))
        self.stateComboBox.setItemText(24, _translate("add_student", "Missouri", None))
        self.stateComboBox.setItemText(25, _translate("add_student", "Montana", None))
        self.stateComboBox.setItemText(26, _translate("add_student", "Nebraska", None))
        self.stateComboBox.setItemText(27, _translate("add_student", "Nevada", None))
        self.stateComboBox.setItemText(28, _translate("add_student", "New Hampshire", None))
        self.stateComboBox.setItemText(29, _translate("add_student", "New Jersey", None))
        self.stateComboBox.setItemText(30, _translate("add_student", "New Mexico", None))
        self.stateComboBox.setItemText(31, _translate("add_student", "New York", None))
        self.stateComboBox.setItemText(32, _translate("add_student", "North Carolina", None))
        self.stateComboBox.setItemText(33, _translate("add_student", "North Dakota", None))
        self.stateComboBox.setItemText(34, _translate("add_student", "Ohio", None))
        self.stateComboBox.setItemText(35, _translate("add_student", "Oklahoma", None))
        self.stateComboBox.setItemText(36, _translate("add_student", "Oregon", None))
        self.stateComboBox.setItemText(37, _translate("add_student", "Pennsylvania", None))
        self.stateComboBox.setItemText(38, _translate("add_student", "Rhode Island", None))
        self.stateComboBox.setItemText(39, _translate("add_student", "South Carolina", None))
        self.stateComboBox.setItemText(40, _translate("add_student", "South Dakota", None))
        self.stateComboBox.setItemText(41, _translate("add_student", "Tennessee", None))
        self.stateComboBox.setItemText(42, _translate("add_student", "Texas", None))
        self.stateComboBox.setItemText(43, _translate("add_student", "Utah", None))
        self.stateComboBox.setItemText(44, _translate("add_student", "Vermont", None))
        self.stateComboBox.setItemText(45, _translate("add_student", "Virginia", None))
        self.stateComboBox.setItemText(46, _translate("add_student", "Washington", None))
        self.stateComboBox.setItemText(47, _translate("add_student", "West Virginia", None))
        self.stateComboBox.setItemText(48, _translate("add_student", "Wisconsin", None))
        self.stateComboBox.setItemText(49, _translate("add_student", "Wyoming", None))
        self.zipcodeLabel.setText(_translate("add_student", "Zipcode*", None))
        self.emailLabel.setText(_translate("add_student", "Email", None))
        self.genderLabel.setText(_translate("add_student", "Gender*", None))
        self.genderComboBox.setItemText(0, _translate("add_student", "Male", None))
        self.genderComboBox.setItemText(1, _translate("add_student", "Female", None))
        self.primaryLabel.setText(_translate("add_student", "Primary Guardian", None))
        self.primaryComboBox.setItemText(0, _translate("add_student", "Add New", None))
        self.secondaryLabel.setText(_translate("add_student", "Secondary Guardian", None))
        self.secondaryComboBox.setItemText(0, _translate("add_student", "Add New", None))
        self.medicalLabel.setText(_translate("add_student", "Medical Information", None))
        self.requiredLabel.setText(_translate("add_student", "* Required Field", None))
        self.Submit_btn.setText(_translate("add_student", "Submit", None))
        self.eContact.setText(_translate("add_student", "Emergency Contact", None))

