# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Modify_guardian.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_add_guardian(object):
    def setupUi(self, add_guardian):
        add_guardian.setObjectName(_fromUtf8("add_guardian"))
        add_guardian.resize(698, 298)
        self.formLayoutWidget = QtGui.QWidget(add_guardian)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 681, 271))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.NameLabel = QtGui.QLabel(self.formLayoutWidget)
        self.NameLabel.setObjectName(_fromUtf8("NameLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.NameLabel)
        self.nameLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nameLineEdit)
        self.homePhoneLabel = QtGui.QLabel(self.formLayoutWidget)
        self.homePhoneLabel.setObjectName(_fromUtf8("homePhoneLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.homePhoneLabel)
        self.homePhoneLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.homePhoneLineEdit.setObjectName(_fromUtf8("homePhoneLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.homePhoneLineEdit)
        self.cellPhoneLabel = QtGui.QLabel(self.formLayoutWidget)
        self.cellPhoneLabel.setObjectName(_fromUtf8("cellPhoneLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.cellPhoneLabel)
        self.cellPhoneLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.cellPhoneLineEdit.setObjectName(_fromUtf8("cellPhoneLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cellPhoneLineEdit)
        self.workPhoneLabel = QtGui.QLabel(self.formLayoutWidget)
        self.workPhoneLabel.setObjectName(_fromUtf8("workPhoneLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.workPhoneLabel)
        self.workPhoneLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.workPhoneLineEdit.setObjectName(_fromUtf8("workPhoneLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.workPhoneLineEdit)
        self.addressLabel = QtGui.QLabel(self.formLayoutWidget)
        self.addressLabel.setObjectName(_fromUtf8("addressLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.addressLabel)
        self.addressLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.addressLineEdit.setObjectName(_fromUtf8("addressLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.addressLineEdit)
        self.cityLabel = QtGui.QLabel(self.formLayoutWidget)
        self.cityLabel.setObjectName(_fromUtf8("cityLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.cityLabel)
        self.cityLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.cityLineEdit.setObjectName(_fromUtf8("cityLineEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.cityLineEdit)
        self.stateLabel = QtGui.QLabel(self.formLayoutWidget)
        self.stateLabel.setObjectName(_fromUtf8("stateLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.stateLabel)
        self.stateComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.stateComboBox.setObjectName(_fromUtf8("stateComboBox"))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.stateComboBox)
        self.zipcodeLabel = QtGui.QLabel(self.formLayoutWidget)
        self.zipcodeLabel.setObjectName(_fromUtf8("zipcodeLabel"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.zipcodeLabel)
        self.zipcodeLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.zipcodeLineEdit.setObjectName(_fromUtf8("zipcodeLineEdit"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.zipcodeLineEdit)
        self.emailLabel = QtGui.QLabel(self.formLayoutWidget)
        self.emailLabel.setObjectName(_fromUtf8("emailLabel"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.emailLabel)
        self.emailLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.emailLineEdit.setObjectName(_fromUtf8("emailLineEdit"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.emailLineEdit)
        self.requiredLabel = QtGui.QLabel(self.formLayoutWidget)
        self.requiredLabel.setObjectName(_fromUtf8("requiredLabel"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.requiredLabel)
        self.Submit_btn = QtGui.QPushButton(self.formLayoutWidget)
        self.Submit_btn.setObjectName(_fromUtf8("Submit_btn"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.Submit_btn)

        self.retranslateUi(add_guardian)
        QtCore.QMetaObject.connectSlotsByName(add_guardian)

    def retranslateUi(self, add_guardian):
        add_guardian.setWindowTitle(_translate("add_guardian", "Modify Guardian", None))
        self.NameLabel.setText(_translate("add_guardian", "Name*", None))
        self.homePhoneLabel.setText(_translate("add_guardian", "Home Phone*", None))
        self.cellPhoneLabel.setText(_translate("add_guardian", "Cell Phone", None))
        self.workPhoneLabel.setText(_translate("add_guardian", "Work Phone", None))
        self.addressLabel.setText(_translate("add_guardian", "Address*", None))
        self.cityLabel.setText(_translate("add_guardian", "City*", None))
        self.stateLabel.setText(_translate("add_guardian", "State*", None))
        self.stateComboBox.setItemText(0, _translate("add_guardian", "Alabama", None))
        self.stateComboBox.setItemText(1, _translate("add_guardian", "Alaska", None))
        self.stateComboBox.setItemText(2, _translate("add_guardian", "Arizona", None))
        self.stateComboBox.setItemText(3, _translate("add_guardian", "Arkansas", None))
        self.stateComboBox.setItemText(4, _translate("add_guardian", "California", None))
        self.stateComboBox.setItemText(5, _translate("add_guardian", "Colorado", None))
        self.stateComboBox.setItemText(6, _translate("add_guardian", "Connecticut", None))
        self.stateComboBox.setItemText(7, _translate("add_guardian", "Delaware", None))
        self.stateComboBox.setItemText(8, _translate("add_guardian", "Florida", None))
        self.stateComboBox.setItemText(9, _translate("add_guardian", "Georgia", None))
        self.stateComboBox.setItemText(10, _translate("add_guardian", "Hawaii", None))
        self.stateComboBox.setItemText(11, _translate("add_guardian", "Idaho", None))
        self.stateComboBox.setItemText(12, _translate("add_guardian", "Illinois", None))
        self.stateComboBox.setItemText(13, _translate("add_guardian", "Indiana", None))
        self.stateComboBox.setItemText(14, _translate("add_guardian", "Iowa", None))
        self.stateComboBox.setItemText(15, _translate("add_guardian", "Kansas", None))
        self.stateComboBox.setItemText(16, _translate("add_guardian", "Kentucky", None))
        self.stateComboBox.setItemText(17, _translate("add_guardian", "Louisiana", None))
        self.stateComboBox.setItemText(18, _translate("add_guardian", "Maine", None))
        self.stateComboBox.setItemText(19, _translate("add_guardian", "Maryland", None))
        self.stateComboBox.setItemText(20, _translate("add_guardian", "Massachusetts", None))
        self.stateComboBox.setItemText(21, _translate("add_guardian", "Michigan", None))
        self.stateComboBox.setItemText(22, _translate("add_guardian", "Minnesota", None))
        self.stateComboBox.setItemText(23, _translate("add_guardian", "Mississippi", None))
        self.stateComboBox.setItemText(24, _translate("add_guardian", "Missouri", None))
        self.stateComboBox.setItemText(25, _translate("add_guardian", "Montana", None))
        self.stateComboBox.setItemText(26, _translate("add_guardian", "Nebraska", None))
        self.stateComboBox.setItemText(27, _translate("add_guardian", "Nevada", None))
        self.stateComboBox.setItemText(28, _translate("add_guardian", "New Hampshire", None))
        self.stateComboBox.setItemText(29, _translate("add_guardian", "New Jersey", None))
        self.stateComboBox.setItemText(30, _translate("add_guardian", "New Mexico", None))
        self.stateComboBox.setItemText(31, _translate("add_guardian", "New York", None))
        self.stateComboBox.setItemText(32, _translate("add_guardian", "North Carolina", None))
        self.stateComboBox.setItemText(33, _translate("add_guardian", "North Dakota", None))
        self.stateComboBox.setItemText(34, _translate("add_guardian", "Ohio", None))
        self.stateComboBox.setItemText(35, _translate("add_guardian", "Oklahoma", None))
        self.stateComboBox.setItemText(36, _translate("add_guardian", "Oregon", None))
        self.stateComboBox.setItemText(37, _translate("add_guardian", "Pennsylvania", None))
        self.stateComboBox.setItemText(38, _translate("add_guardian", "Rhode Island", None))
        self.stateComboBox.setItemText(39, _translate("add_guardian", "South Carolina", None))
        self.stateComboBox.setItemText(40, _translate("add_guardian", "South Dakota", None))
        self.stateComboBox.setItemText(41, _translate("add_guardian", "Tennessee", None))
        self.stateComboBox.setItemText(42, _translate("add_guardian", "Texas", None))
        self.stateComboBox.setItemText(43, _translate("add_guardian", "Utah", None))
        self.stateComboBox.setItemText(44, _translate("add_guardian", "Vermont", None))
        self.stateComboBox.setItemText(45, _translate("add_guardian", "Virginia", None))
        self.stateComboBox.setItemText(46, _translate("add_guardian", "Washington", None))
        self.stateComboBox.setItemText(47, _translate("add_guardian", "West Virginia", None))
        self.stateComboBox.setItemText(48, _translate("add_guardian", "Wisconsin", None))
        self.stateComboBox.setItemText(49, _translate("add_guardian", "Wyoming", None))
        self.zipcodeLabel.setText(_translate("add_guardian", "Zipcode*", None))
        self.emailLabel.setText(_translate("add_guardian", "Email", None))
        self.requiredLabel.setText(_translate("add_guardian", "* Required Field", None))
        self.Submit_btn.setText(_translate("add_guardian", "Submit", None))

