# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Teacher_info.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Teacher_info_dialog(object):
    def setupUi(self, Teacher_info_dialog):
        Teacher_info_dialog.setObjectName(_fromUtf8("Teacher_info_dialog"))
        Teacher_info_dialog.resize(784, 491)
        self.Id_detail_label = QtGui.QLabel(Teacher_info_dialog)
        self.Id_detail_label.setGeometry(QtCore.QRect(20, 50, 54, 12))
        self.Id_detail_label.setObjectName(_fromUtf8("Id_detail_label"))
        self.Gender_detail_label = QtGui.QLabel(Teacher_info_dialog)
        self.Gender_detail_label.setGeometry(QtCore.QRect(20, 90, 54, 12))
        self.Gender_detail_label.setObjectName(_fromUtf8("Gender_detail_label"))
        self.Birth_detail_label = QtGui.QLabel(Teacher_info_dialog)
        self.Birth_detail_label.setGeometry(QtCore.QRect(20, 130, 61, 16))
        self.Birth_detail_label.setObjectName(_fromUtf8("Birth_detail_label"))
        self.Cellphone_detail_label = QtGui.QLabel(Teacher_info_dialog)
        self.Cellphone_detail_label.setGeometry(QtCore.QRect(20, 170, 101, 16))
        self.Cellphone_detail_label.setObjectName(_fromUtf8("Cellphone_detail_label"))
        self.SNN_detail_label = QtGui.QLabel(Teacher_info_dialog)
        self.SNN_detail_label.setGeometry(QtCore.QRect(20, 210, 101, 16))
        self.SNN_detail_label.setObjectName(_fromUtf8("SNN_detail_label"))
        self.Zipcode_detail_label = QtGui.QLabel(Teacher_info_dialog)
        self.Zipcode_detail_label.setGeometry(QtCore.QRect(20, 250, 101, 16))
        self.Zipcode_detail_label.setObjectName(_fromUtf8("Zipcode_detail_label"))
        self.Address_detail_label = QtGui.QLabel(Teacher_info_dialog)
        self.Address_detail_label.setGeometry(QtCore.QRect(20, 290, 54, 12))
        self.Address_detail_label.setObjectName(_fromUtf8("Address_detail_label"))
        self.Name_detail_label = QtGui.QLabel(Teacher_info_dialog)
        self.Name_detail_label.setGeometry(QtCore.QRect(380, 50, 54, 12))
        self.Name_detail_label.setObjectName(_fromUtf8("Name_detail_label"))
        self.Email_detail_label = QtGui.QLabel(Teacher_info_dialog)
        self.Email_detail_label.setGeometry(QtCore.QRect(380, 90, 54, 12))
        self.Email_detail_label.setObjectName(_fromUtf8("Email_detail_label"))
        self.Homephone_detail_label = QtGui.QLabel(Teacher_info_dialog)
        self.Homephone_detail_label.setGeometry(QtCore.QRect(380, 130, 81, 16))
        self.Homephone_detail_label.setObjectName(_fromUtf8("Homephone_detail_label"))
        self.Workphone_detail_label = QtGui.QLabel(Teacher_info_dialog)
        self.Workphone_detail_label.setGeometry(QtCore.QRect(380, 170, 111, 16))
        self.Workphone_detail_label.setObjectName(_fromUtf8("Workphone_detail_label"))
        self.Id_detail_lineEdit = QtGui.QLineEdit(Teacher_info_dialog)
        self.Id_detail_lineEdit.setGeometry(QtCore.QRect(130, 50, 221, 20))
        self.Id_detail_lineEdit.setObjectName(_fromUtf8("Id_detail_lineEdit"))
        self.Cellphone_detail_lineEdit = QtGui.QLineEdit(Teacher_info_dialog)
        self.Cellphone_detail_lineEdit.setGeometry(QtCore.QRect(130, 170, 221, 20))
        self.Cellphone_detail_lineEdit.setObjectName(_fromUtf8("Cellphone_detail_lineEdit"))
        self.SSN_detail_lineEdit = QtGui.QLineEdit(Teacher_info_dialog)
        self.SSN_detail_lineEdit.setGeometry(QtCore.QRect(130, 210, 221, 20))
        self.SSN_detail_lineEdit.setObjectName(_fromUtf8("SSN_detail_lineEdit"))
        self.Zipcode_detail_lineEdit = QtGui.QLineEdit(Teacher_info_dialog)
        self.Zipcode_detail_lineEdit.setGeometry(QtCore.QRect(130, 250, 221, 20))
        self.Zipcode_detail_lineEdit.setObjectName(_fromUtf8("Zipcode_detail_lineEdit"))
        self.Homephone_detail_lineEdit = QtGui.QLineEdit(Teacher_info_dialog)
        self.Homephone_detail_lineEdit.setGeometry(QtCore.QRect(500, 130, 221, 20))
        self.Homephone_detail_lineEdit.setObjectName(_fromUtf8("Homephone_detail_lineEdit"))
        self.Name_detail_lineEdit = QtGui.QLineEdit(Teacher_info_dialog)
        self.Name_detail_lineEdit.setGeometry(QtCore.QRect(500, 50, 221, 20))
        self.Name_detail_lineEdit.setObjectName(_fromUtf8("Name_detail_lineEdit"))
        self.Workphone_detail_lineEdit = QtGui.QLineEdit(Teacher_info_dialog)
        self.Workphone_detail_lineEdit.setGeometry(QtCore.QRect(500, 170, 221, 20))
        self.Workphone_detail_lineEdit.setObjectName(_fromUtf8("Workphone_detail_lineEdit"))
        self.Email_detail_lineEdit = QtGui.QLineEdit(Teacher_info_dialog)
        self.Email_detail_lineEdit.setGeometry(QtCore.QRect(500, 90, 221, 20))
        self.Email_detail_lineEdit.setObjectName(_fromUtf8("Email_detail_lineEdit"))
        self.Close_detail_btn = QtGui.QPushButton(Teacher_info_dialog)
        self.Close_detail_btn.setGeometry(QtCore.QRect(540, 460, 91, 21))
        self.Close_detail_btn.setObjectName(_fromUtf8("Close_detail_btn"))
        self.Medical_detail_label = QtGui.QLabel(Teacher_info_dialog)
        self.Medical_detail_label.setGeometry(QtCore.QRect(380, 210, 121, 16))
        self.Medical_detail_label.setObjectName(_fromUtf8("Medical_detail_label"))
        self.Update_detail_btn = QtGui.QPushButton(Teacher_info_dialog)
        self.Update_detail_btn.setGeometry(QtCore.QRect(660, 460, 91, 21))
        self.Update_detail_btn.setObjectName(_fromUtf8("Update_detail_btn"))
        self.Medical_detail_textEdit = QtGui.QTextEdit(Teacher_info_dialog)
        self.Medical_detail_textEdit.setGeometry(QtCore.QRect(500, 210, 221, 181))
        self.Medical_detail_textEdit.setObjectName(_fromUtf8("Medical_detail_textEdit"))
        self.Address_detail_lineEdit = QtGui.QLineEdit(Teacher_info_dialog)
        self.Address_detail_lineEdit.setGeometry(QtCore.QRect(130, 290, 221, 20))
        self.Address_detail_lineEdit.setObjectName(_fromUtf8("Address_detail_lineEdit"))
        self.City_detail_label = QtGui.QLabel(Teacher_info_dialog)
        self.City_detail_label.setGeometry(QtCore.QRect(20, 330, 54, 12))
        self.City_detail_label.setObjectName(_fromUtf8("City_detail_label"))
        self.State_detail_label_3 = QtGui.QLabel(Teacher_info_dialog)
        self.State_detail_label_3.setGeometry(QtCore.QRect(20, 370, 54, 12))
        self.State_detail_label_3.setObjectName(_fromUtf8("State_detail_label_3"))
        self.City_detail_lineEdit = QtGui.QLineEdit(Teacher_info_dialog)
        self.City_detail_lineEdit.setGeometry(QtCore.QRect(130, 330, 221, 20))
        self.City_detail_lineEdit.setObjectName(_fromUtf8("City_detail_lineEdit"))
        self.Birth_detail_dateEdit = QtGui.QDateEdit(Teacher_info_dialog)
        self.Birth_detail_dateEdit.setGeometry(QtCore.QRect(130, 130, 221, 22))
        self.Birth_detail_dateEdit.setObjectName(_fromUtf8("Birth_detail_dateEdit"))
        self.Gender_comboBox = QtGui.QComboBox(Teacher_info_dialog)
        self.Gender_comboBox.setGeometry(QtCore.QRect(130, 90, 221, 22))
        self.Gender_comboBox.setObjectName(_fromUtf8("Gender_comboBox"))
        self.State_detail_ComboBox = QtGui.QComboBox(Teacher_info_dialog)
        self.State_detail_ComboBox.setGeometry(QtCore.QRect(130, 370, 221, 20))
        self.State_detail_ComboBox.setObjectName(_fromUtf8("State_detail_ComboBox"))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))
        self.State_detail_ComboBox.addItem(_fromUtf8(""))

        self.retranslateUi(Teacher_info_dialog)
        QtCore.QMetaObject.connectSlotsByName(Teacher_info_dialog)

    def retranslateUi(self, Teacher_info_dialog):
        Teacher_info_dialog.setWindowTitle(_translate("Teacher_info_dialog", "Teacher Information", None))
        self.Id_detail_label.setText(_translate("Teacher_info_dialog", "ID", None))
        self.Gender_detail_label.setText(_translate("Teacher_info_dialog", "Gender", None))
        self.Birth_detail_label.setText(_translate("Teacher_info_dialog", "Date Birth", None))
        self.Cellphone_detail_label.setText(_translate("Teacher_info_dialog", "Cell Phone", None))
        self.SNN_detail_label.setText(_translate("Teacher_info_dialog", "SSN", None))
        self.Zipcode_detail_label.setText(_translate("Teacher_info_dialog", "Zipcode", None))
        self.Address_detail_label.setText(_translate("Teacher_info_dialog", "Address", None))
        self.Name_detail_label.setText(_translate("Teacher_info_dialog", "Name", None))
        self.Email_detail_label.setText(_translate("Teacher_info_dialog", "Email", None))
        self.Homephone_detail_label.setText(_translate("Teacher_info_dialog", "Home Phone", None))
        self.Workphone_detail_label.setText(_translate("Teacher_info_dialog", "Work Phone", None))
        self.Close_detail_btn.setText(_translate("Teacher_info_dialog", "Close", None))
        self.Medical_detail_label.setText(_translate("Teacher_info_dialog", "Medical Information", None))
        self.Update_detail_btn.setText(_translate("Teacher_info_dialog", "Update", None))
        self.City_detail_label.setText(_translate("Teacher_info_dialog", "City", None))
        self.State_detail_label_3.setText(_translate("Teacher_info_dialog", "State", None))
        self.State_detail_ComboBox.setItemText(0, _translate("Teacher_info_dialog", "Alabama", None))
        self.State_detail_ComboBox.setItemText(1, _translate("Teacher_info_dialog", "Alaska", None))
        self.State_detail_ComboBox.setItemText(2, _translate("Teacher_info_dialog", "Arizona", None))
        self.State_detail_ComboBox.setItemText(3, _translate("Teacher_info_dialog", "Arkansas", None))
        self.State_detail_ComboBox.setItemText(4, _translate("Teacher_info_dialog", "California", None))
        self.State_detail_ComboBox.setItemText(5, _translate("Teacher_info_dialog", "Colorado", None))
        self.State_detail_ComboBox.setItemText(6, _translate("Teacher_info_dialog", "Connecticut", None))
        self.State_detail_ComboBox.setItemText(7, _translate("Teacher_info_dialog", "Delaware", None))
        self.State_detail_ComboBox.setItemText(8, _translate("Teacher_info_dialog", "Florida", None))
        self.State_detail_ComboBox.setItemText(9, _translate("Teacher_info_dialog", "Georgia", None))
        self.State_detail_ComboBox.setItemText(10, _translate("Teacher_info_dialog", "Hawaii", None))
        self.State_detail_ComboBox.setItemText(11, _translate("Teacher_info_dialog", "Idaho", None))
        self.State_detail_ComboBox.setItemText(12, _translate("Teacher_info_dialog", "Illinois", None))
        self.State_detail_ComboBox.setItemText(13, _translate("Teacher_info_dialog", "Indiana", None))
        self.State_detail_ComboBox.setItemText(14, _translate("Teacher_info_dialog", "Iowa", None))
        self.State_detail_ComboBox.setItemText(15, _translate("Teacher_info_dialog", "Kansas", None))
        self.State_detail_ComboBox.setItemText(16, _translate("Teacher_info_dialog", "Kentucky", None))
        self.State_detail_ComboBox.setItemText(17, _translate("Teacher_info_dialog", "Louisiana", None))
        self.State_detail_ComboBox.setItemText(18, _translate("Teacher_info_dialog", "Maine", None))
        self.State_detail_ComboBox.setItemText(19, _translate("Teacher_info_dialog", "Maryland", None))
        self.State_detail_ComboBox.setItemText(20, _translate("Teacher_info_dialog", "Massachusetts", None))
        self.State_detail_ComboBox.setItemText(21, _translate("Teacher_info_dialog", "Michigan", None))
        self.State_detail_ComboBox.setItemText(22, _translate("Teacher_info_dialog", "Minnesota", None))
        self.State_detail_ComboBox.setItemText(23, _translate("Teacher_info_dialog", "Mississippi", None))
        self.State_detail_ComboBox.setItemText(24, _translate("Teacher_info_dialog", "Missouri", None))
        self.State_detail_ComboBox.setItemText(25, _translate("Teacher_info_dialog", "Montana", None))
        self.State_detail_ComboBox.setItemText(26, _translate("Teacher_info_dialog", "Nebraska", None))
        self.State_detail_ComboBox.setItemText(27, _translate("Teacher_info_dialog", "Nevada", None))
        self.State_detail_ComboBox.setItemText(28, _translate("Teacher_info_dialog", "New Hampshire", None))
        self.State_detail_ComboBox.setItemText(29, _translate("Teacher_info_dialog", "New Jersey", None))
        self.State_detail_ComboBox.setItemText(30, _translate("Teacher_info_dialog", "New Mexico", None))
        self.State_detail_ComboBox.setItemText(31, _translate("Teacher_info_dialog", "New York", None))
        self.State_detail_ComboBox.setItemText(32, _translate("Teacher_info_dialog", "North Carolina", None))
        self.State_detail_ComboBox.setItemText(33, _translate("Teacher_info_dialog", "North Dakota", None))
        self.State_detail_ComboBox.setItemText(34, _translate("Teacher_info_dialog", "Ohio", None))
        self.State_detail_ComboBox.setItemText(35, _translate("Teacher_info_dialog", "Oklahoma", None))
        self.State_detail_ComboBox.setItemText(36, _translate("Teacher_info_dialog", "Oregon", None))
        self.State_detail_ComboBox.setItemText(37, _translate("Teacher_info_dialog", "Pennsylvania", None))
        self.State_detail_ComboBox.setItemText(38, _translate("Teacher_info_dialog", "Rhode Island", None))
        self.State_detail_ComboBox.setItemText(39, _translate("Teacher_info_dialog", "South Carolina", None))
        self.State_detail_ComboBox.setItemText(40, _translate("Teacher_info_dialog", "South Dakota", None))
        self.State_detail_ComboBox.setItemText(41, _translate("Teacher_info_dialog", "Tennessee", None))
        self.State_detail_ComboBox.setItemText(42, _translate("Teacher_info_dialog", "Texas", None))
        self.State_detail_ComboBox.setItemText(43, _translate("Teacher_info_dialog", "Utah", None))
        self.State_detail_ComboBox.setItemText(44, _translate("Teacher_info_dialog", "Vermont", None))
        self.State_detail_ComboBox.setItemText(45, _translate("Teacher_info_dialog", "Virginia", None))
        self.State_detail_ComboBox.setItemText(46, _translate("Teacher_info_dialog", "Washington", None))
        self.State_detail_ComboBox.setItemText(47, _translate("Teacher_info_dialog", "West Virginia", None))
        self.State_detail_ComboBox.setItemText(48, _translate("Teacher_info_dialog", "Wisconsin", None))
        self.State_detail_ComboBox.setItemText(49, _translate("Teacher_info_dialog", "Wyoming", None))

