# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Teacher Landing.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Teacher_Landing(object):
    def setupUi(self, Teacher_Landing):
        Teacher_Landing.setObjectName(_fromUtf8("Teacher_Landing"))
        Teacher_Landing.resize(558, 335)
        self.centralwidget = QtGui.QWidget(Teacher_Landing)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 531, 311))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.Teacher_page = QtGui.QWidget()
        self.Teacher_page.setObjectName(_fromUtf8("Teacher_page"))
        self.verticalLayoutWidget = QtGui.QWidget(self.Teacher_page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 521, 311))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.Quit_btn = QtGui.QPushButton(self.groupBox_2)
        self.Quit_btn.setGeometry(QtCore.QRect(420, 250, 75, 23))
        font = QtGui.QFont()
        font.setItalic(True)
        self.Quit_btn.setFont(font)
        self.Quit_btn.setObjectName(_fromUtf8("Quit_btn"))
        self.Logout_btn = QtGui.QPushButton(self.groupBox_2)
        self.Logout_btn.setGeometry(QtCore.QRect(340, 250, 75, 23))
        font = QtGui.QFont()
        font.setItalic(True)
        self.Logout_btn.setFont(font)
        self.Logout_btn.setObjectName(_fromUtf8("Logout_btn"))
        self.Student_btn = QtGui.QPushButton(self.groupBox_2)
        self.Student_btn.setGeometry(QtCore.QRect(90, 40, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Student_btn.setFont(font)
        self.Student_btn.setObjectName(_fromUtf8("Student_btn"))
        self.Personal_btn = QtGui.QPushButton(self.groupBox_2)
        self.Personal_btn.setGeometry(QtCore.QRect(90, 180, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.Personal_btn.setFont(font)
        self.Personal_btn.setObjectName(_fromUtf8("Personal_btn"))
        self.Class_btn = QtGui.QPushButton(self.groupBox_2)
        self.Class_btn.setGeometry(QtCore.QRect(90, 110, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.Class_btn.setFont(font)
        self.Class_btn.setObjectName(_fromUtf8("Class_btn"))
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.stackedWidget.addWidget(self.Teacher_page)
        self.Student_page = QtGui.QWidget()
        self.Student_page.setObjectName(_fromUtf8("Student_page"))
        self.Student_back_btn = QtGui.QPushButton(self.Student_page)
        self.Student_back_btn.setGeometry(QtCore.QRect(340, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Student_back_btn.setFont(font)
        self.Student_back_btn.setObjectName(_fromUtf8("Student_back_btn"))
        self.Student_quit_btn = QtGui.QPushButton(self.Student_page)
        self.Student_quit_btn.setGeometry(QtCore.QRect(420, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Student_quit_btn.setFont(font)
        self.Student_quit_btn.setObjectName(_fromUtf8("Student_quit_btn"))
        self.Search_student_btn = QtGui.QPushButton(self.Student_page)
        self.Search_student_btn.setGeometry(QtCore.QRect(90, 50, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Search_student_btn.setFont(font)
        self.Search_student_btn.setObjectName(_fromUtf8("Search_student_btn"))
        self.Add_class_btn = QtGui.QPushButton(self.Student_page)
        self.Add_class_btn.setGeometry(QtCore.QRect(90, 120, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Add_class_btn.setFont(font)
        self.Add_class_btn.setObjectName(_fromUtf8("Add_class_btn"))
        self.See_student_schedule_btn = QtGui.QPushButton(self.Student_page)
        self.See_student_schedule_btn.setGeometry(QtCore.QRect(90, 190, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.See_student_schedule_btn.setFont(font)
        self.See_student_schedule_btn.setObjectName(_fromUtf8("See_student_schedule_btn"))
        self.stackedWidget.addWidget(self.Student_page)
        self.Class_page = QtGui.QWidget()
        self.Class_page.setObjectName(_fromUtf8("Class_page"))
        self.Class_back_btn = QtGui.QPushButton(self.Class_page)
        self.Class_back_btn.setGeometry(QtCore.QRect(340, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.Class_back_btn.setFont(font)
        self.Class_back_btn.setObjectName(_fromUtf8("Class_back_btn"))
        self.Class_quit_btn = QtGui.QPushButton(self.Class_page)
        self.Class_quit_btn.setGeometry(QtCore.QRect(420, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Class_quit_btn.setFont(font)
        self.Class_quit_btn.setObjectName(_fromUtf8("Class_quit_btn"))
        self.See_class_schedule_btn = QtGui.QPushButton(self.Class_page)
        self.See_class_schedule_btn.setGeometry(QtCore.QRect(90, 40, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.See_class_schedule_btn.setFont(font)
        self.See_class_schedule_btn.setObjectName(_fromUtf8("See_class_schedule_btn"))
        self.See_class_info_btn = QtGui.QPushButton(self.Class_page)
        self.See_class_info_btn.setGeometry(QtCore.QRect(90, 110, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.See_class_info_btn.setFont(font)
        self.See_class_info_btn.setObjectName(_fromUtf8("See_class_info_btn"))
        self.See_class_role_btn = QtGui.QPushButton(self.Class_page)
        self.See_class_role_btn.setGeometry(QtCore.QRect(90, 180, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.See_class_role_btn.setFont(font)
        self.See_class_role_btn.setObjectName(_fromUtf8("See_class_role_btn"))
        self.stackedWidget.addWidget(self.Class_page)
        self.Personal_page = QtGui.QWidget()
        self.Personal_page.setObjectName(_fromUtf8("Personal_page"))
        self.Personal_back_btn = QtGui.QPushButton(self.Personal_page)
        self.Personal_back_btn.setGeometry(QtCore.QRect(340, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.Personal_back_btn.setFont(font)
        self.Personal_back_btn.setObjectName(_fromUtf8("Personal_back_btn"))
        self.Personal_quit_btn = QtGui.QPushButton(self.Personal_page)
        self.Personal_quit_btn.setGeometry(QtCore.QRect(420, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Personal_quit_btn.setFont(font)
        self.Personal_quit_btn.setObjectName(_fromUtf8("Personal_quit_btn"))
        self.Enter_hours_btn = QtGui.QPushButton(self.Personal_page)
        self.Enter_hours_btn.setGeometry(QtCore.QRect(90, 40, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Enter_hours_btn.setFont(font)
        self.Enter_hours_btn.setObjectName(_fromUtf8("Enter_hours_btn"))
        self.Modify_personal_info = QtGui.QPushButton(self.Personal_page)
        self.Modify_personal_info.setGeometry(QtCore.QRect(90, 110, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Modify_personal_info.setFont(font)
        self.Modify_personal_info.setObjectName(_fromUtf8("Modify_personal_info"))
        self.Reset_password = QtGui.QPushButton(self.Personal_page)
        self.Reset_password.setGeometry(QtCore.QRect(90, 180, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Reset_password.setFont(font)
        self.Reset_password.setObjectName(_fromUtf8("Reset_password"))
        self.stackedWidget.addWidget(self.Personal_page)
        Teacher_Landing.setCentralWidget(self.centralwidget)

        self.retranslateUi(Teacher_Landing)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Teacher_Landing)

    def retranslateUi(self, Teacher_Landing):
        Teacher_Landing.setWindowTitle(_translate("Teacher_Landing", "Teacher Landing", None))
        self.groupBox_2.setTitle(_translate("Teacher_Landing", "Teachers", None))
        self.Quit_btn.setText(_translate("Teacher_Landing", "Quit", None))
        self.Logout_btn.setText(_translate("Teacher_Landing", "Logout", None))
        self.Student_btn.setText(_translate("Teacher_Landing", "Student Options", None))
        self.Personal_btn.setText(_translate("Teacher_Landing", "Personal Options", None))
        self.Class_btn.setText(_translate("Teacher_Landing", "Class Options", None))
        self.Student_back_btn.setText(_translate("Teacher_Landing", "Back", None))
        self.Student_quit_btn.setText(_translate("Teacher_Landing", "Quit", None))
        self.Search_student_btn.setText(_translate("Teacher_Landing", "Search for Student", None))
        self.Add_class_btn.setText(_translate("Teacher_Landing", "Request Add to Class", None))
        self.See_student_schedule_btn.setText(_translate("Teacher_Landing", "See Schedule", None))
        self.Class_back_btn.setText(_translate("Teacher_Landing", "Back", None))
        self.Class_quit_btn.setText(_translate("Teacher_Landing", "Quit", None))
        self.See_class_schedule_btn.setText(_translate("Teacher_Landing", "See Schedule", None))
        self.See_class_info_btn.setText(_translate("Teacher_Landing", "See Class Info", None))
        self.See_class_role_btn.setText(_translate("Teacher_Landing", "See Class Role Sheet", None))
        self.Personal_back_btn.setText(_translate("Teacher_Landing", "Back", None))
        self.Personal_quit_btn.setText(_translate("Teacher_Landing", "Quit", None))
        self.Enter_hours_btn.setText(_translate("Teacher_Landing", "Enter Hours", None))
        self.Modify_personal_info.setText(_translate("Teacher_Landing", "Modify Personal Info", None))
        self.Reset_password.setText(_translate("Teacher_Landing", "Reset Password", None))

