# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Update_Teacher.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_modify_teacher(object):
    def setupUi(self, modify_teacher):
        modify_teacher.setObjectName(_fromUtf8("modify_teacher"))
        modify_teacher.resize(720, 538)
        self.formLayoutWidget = QtGui.QWidget(modify_teacher)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 701, 521))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.selectTeacherLabel = QtGui.QLabel(self.formLayoutWidget)
        self.selectTeacherLabel.setObjectName(_fromUtf8("selectTeacherLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.selectTeacherLabel)
        self.selectTeacherComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.selectTeacherComboBox.setObjectName(_fromUtf8("selectTeacherComboBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.selectTeacherComboBox)
        self.NameLabel = QtGui.QLabel(self.formLayoutWidget)
        self.NameLabel.setObjectName(_fromUtf8("NameLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.NameLabel)
        self.nameLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.nameLineEdit)
        self.homePhoneLabel = QtGui.QLabel(self.formLayoutWidget)
        self.homePhoneLabel.setObjectName(_fromUtf8("homePhoneLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.homePhoneLabel)
        self.cellPhoneLabel = QtGui.QLabel(self.formLayoutWidget)
        self.cellPhoneLabel.setObjectName(_fromUtf8("cellPhoneLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.cellPhoneLabel)
        self.cellPhoneLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.cellPhoneLineEdit.setObjectName(_fromUtf8("cellPhoneLineEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.cellPhoneLineEdit)
        self.workPhoneLabel = QtGui.QLabel(self.formLayoutWidget)
        self.workPhoneLabel.setObjectName(_fromUtf8("workPhoneLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.workPhoneLabel)
        self.workPhoneLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.workPhoneLineEdit.setObjectName(_fromUtf8("workPhoneLineEdit"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.workPhoneLineEdit)
        self.addressLabel = QtGui.QLabel(self.formLayoutWidget)
        self.addressLabel.setObjectName(_fromUtf8("addressLabel"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.addressLabel)
        self.addressLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.addressLineEdit.setObjectName(_fromUtf8("addressLineEdit"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.addressLineEdit)
        self.cityLabel = QtGui.QLabel(self.formLayoutWidget)
        self.cityLabel.setObjectName(_fromUtf8("cityLabel"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.cityLabel)
        self.cityLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.cityLineEdit.setObjectName(_fromUtf8("cityLineEdit"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.cityLineEdit)
        self.stateLabel = QtGui.QLabel(self.formLayoutWidget)
        self.stateLabel.setObjectName(_fromUtf8("stateLabel"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.stateLabel)
        self.stateComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.stateComboBox.setObjectName(_fromUtf8("stateComboBox"))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.stateComboBox)
        self.emailLabel = QtGui.QLabel(self.formLayoutWidget)
        self.emailLabel.setObjectName(_fromUtf8("emailLabel"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.emailLabel)
        self.emailLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.emailLineEdit.setObjectName(_fromUtf8("emailLineEdit"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.emailLineEdit)
        self.genderLabel = QtGui.QLabel(self.formLayoutWidget)
        self.genderLabel.setObjectName(_fromUtf8("genderLabel"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.genderLabel)
        self.genderComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.genderComboBox.setObjectName(_fromUtf8("genderComboBox"))
        self.genderComboBox.addItem(_fromUtf8(""))
        self.genderComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.genderComboBox)
        self.SSNLabel = QtGui.QLabel(self.formLayoutWidget)
        self.SSNLabel.setObjectName(_fromUtf8("SSNLabel"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.SSNLabel)
        self.SSNLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.SSNLineEdit.setObjectName(_fromUtf8("SSNLineEdit"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.SSNLineEdit)
        self.payRateLabel = QtGui.QLabel(self.formLayoutWidget)
        self.payRateLabel.setObjectName(_fromUtf8("payRateLabel"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.payRateLabel)
        self.payRateDoubleSpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.payRateDoubleSpinBox.setSingleStep(0.01)
        self.payRateDoubleSpinBox.setObjectName(_fromUtf8("payRateDoubleSpinBox"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.payRateDoubleSpinBox)
        self.medicalLabel = QtGui.QLabel(self.formLayoutWidget)
        self.medicalLabel.setObjectName(_fromUtf8("medicalLabel"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.LabelRole, self.medicalLabel)
        self.medicalTextEdit = QtGui.QTextEdit(self.formLayoutWidget)
        self.medicalTextEdit.setObjectName(_fromUtf8("medicalTextEdit"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.medicalTextEdit)
        self.requiredLabel = QtGui.QLabel(self.formLayoutWidget)
        self.requiredLabel.setObjectName(_fromUtf8("requiredLabel"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.LabelRole, self.requiredLabel)
        self.Submit_btn = QtGui.QPushButton(self.formLayoutWidget)
        self.Submit_btn.setObjectName(_fromUtf8("Submit_btn"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.FieldRole, self.Submit_btn)
        self.homePhoneLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.homePhoneLineEdit.setObjectName(_fromUtf8("homePhoneLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.homePhoneLineEdit)
        self.Select_teacher_btn = QtGui.QPushButton(self.formLayoutWidget)
        self.Select_teacher_btn.setObjectName(_fromUtf8("Select_teacher_btn"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.Select_teacher_btn)
        self.DOBDateEdit = QtGui.QDateEdit(self.formLayoutWidget)
        self.DOBDateEdit.setDate(QtCore.QDate(1970, 1, 1))
        self.DOBDateEdit.setObjectName(_fromUtf8("DOBDateEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.DOBDateEdit)
        self.DOBlabel = QtGui.QLabel(self.formLayoutWidget)
        self.DOBlabel.setObjectName(_fromUtf8("DOBlabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.DOBlabel)
        self.zipcodeLabel = QtGui.QLabel(self.formLayoutWidget)
        self.zipcodeLabel.setObjectName(_fromUtf8("zipcodeLabel"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.zipcodeLabel)
        self.zipLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.zipLineEdit.setObjectName(_fromUtf8("zipLineEdit"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.zipLineEdit)

        self.retranslateUi(modify_teacher)
        QtCore.QMetaObject.connectSlotsByName(modify_teacher)

    def retranslateUi(self, modify_teacher):
        modify_teacher.setWindowTitle(_translate("modify_teacher", "Update Teacher", None))
        self.selectTeacherLabel.setText(_translate("modify_teacher", "Select Teacher", None))
        self.NameLabel.setText(_translate("modify_teacher", "Name*", None))
        self.homePhoneLabel.setText(_translate("modify_teacher", "Home Phone*", None))
        self.cellPhoneLabel.setText(_translate("modify_teacher", "Cell Phone", None))
        self.workPhoneLabel.setText(_translate("modify_teacher", "Work Phone", None))
        self.addressLabel.setText(_translate("modify_teacher", "Address*", None))
        self.cityLabel.setText(_translate("modify_teacher", "City*", None))
        self.stateLabel.setText(_translate("modify_teacher", "State*", None))
        self.stateComboBox.setItemText(0, _translate("modify_teacher", "Alabama", None))
        self.stateComboBox.setItemText(1, _translate("modify_teacher", "Alaska", None))
        self.stateComboBox.setItemText(2, _translate("modify_teacher", "Arizona", None))
        self.stateComboBox.setItemText(3, _translate("modify_teacher", "Arkansas", None))
        self.stateComboBox.setItemText(4, _translate("modify_teacher", "California", None))
        self.stateComboBox.setItemText(5, _translate("modify_teacher", "Colorado", None))
        self.stateComboBox.setItemText(6, _translate("modify_teacher", "Connecticut", None))
        self.stateComboBox.setItemText(7, _translate("modify_teacher", "Delaware", None))
        self.stateComboBox.setItemText(8, _translate("modify_teacher", "Florida", None))
        self.stateComboBox.setItemText(9, _translate("modify_teacher", "Georgia", None))
        self.stateComboBox.setItemText(10, _translate("modify_teacher", "Hawaii", None))
        self.stateComboBox.setItemText(11, _translate("modify_teacher", "Idaho", None))
        self.stateComboBox.setItemText(12, _translate("modify_teacher", "Illinois", None))
        self.stateComboBox.setItemText(13, _translate("modify_teacher", "Indiana", None))
        self.stateComboBox.setItemText(14, _translate("modify_teacher", "Iowa", None))
        self.stateComboBox.setItemText(15, _translate("modify_teacher", "Kansas", None))
        self.stateComboBox.setItemText(16, _translate("modify_teacher", "Kentucky", None))
        self.stateComboBox.setItemText(17, _translate("modify_teacher", "Louisiana", None))
        self.stateComboBox.setItemText(18, _translate("modify_teacher", "Maine", None))
        self.stateComboBox.setItemText(19, _translate("modify_teacher", "Maryland", None))
        self.stateComboBox.setItemText(20, _translate("modify_teacher", "Massachusetts", None))
        self.stateComboBox.setItemText(21, _translate("modify_teacher", "Michigan", None))
        self.stateComboBox.setItemText(22, _translate("modify_teacher", "Minnesota", None))
        self.stateComboBox.setItemText(23, _translate("modify_teacher", "Mississippi", None))
        self.stateComboBox.setItemText(24, _translate("modify_teacher", "Missouri", None))
        self.stateComboBox.setItemText(25, _translate("modify_teacher", "Montana", None))
        self.stateComboBox.setItemText(26, _translate("modify_teacher", "Nebraska", None))
        self.stateComboBox.setItemText(27, _translate("modify_teacher", "Nevada", None))
        self.stateComboBox.setItemText(28, _translate("modify_teacher", "New Hampshire", None))
        self.stateComboBox.setItemText(29, _translate("modify_teacher", "New Jersey", None))
        self.stateComboBox.setItemText(30, _translate("modify_teacher", "New Mexico", None))
        self.stateComboBox.setItemText(31, _translate("modify_teacher", "New York", None))
        self.stateComboBox.setItemText(32, _translate("modify_teacher", "North Carolina", None))
        self.stateComboBox.setItemText(33, _translate("modify_teacher", "North Dakota", None))
        self.stateComboBox.setItemText(34, _translate("modify_teacher", "Ohio", None))
        self.stateComboBox.setItemText(35, _translate("modify_teacher", "Oklahoma", None))
        self.stateComboBox.setItemText(36, _translate("modify_teacher", "Oregon", None))
        self.stateComboBox.setItemText(37, _translate("modify_teacher", "Pennsylvania", None))
        self.stateComboBox.setItemText(38, _translate("modify_teacher", "Rhode Island", None))
        self.stateComboBox.setItemText(39, _translate("modify_teacher", "South Carolina", None))
        self.stateComboBox.setItemText(40, _translate("modify_teacher", "South Dakota", None))
        self.stateComboBox.setItemText(41, _translate("modify_teacher", "Tennessee", None))
        self.stateComboBox.setItemText(42, _translate("modify_teacher", "Texas", None))
        self.stateComboBox.setItemText(43, _translate("modify_teacher", "Utah", None))
        self.stateComboBox.setItemText(44, _translate("modify_teacher", "Vermont", None))
        self.stateComboBox.setItemText(45, _translate("modify_teacher", "Virginia", None))
        self.stateComboBox.setItemText(46, _translate("modify_teacher", "Washington", None))
        self.stateComboBox.setItemText(47, _translate("modify_teacher", "West Virginia", None))
        self.stateComboBox.setItemText(48, _translate("modify_teacher", "Wisconsin", None))
        self.stateComboBox.setItemText(49, _translate("modify_teacher", "Wyoming", None))
        self.emailLabel.setText(_translate("modify_teacher", "Email", None))
        self.genderLabel.setText(_translate("modify_teacher", "Gender", None))
        self.genderComboBox.setItemText(0, _translate("modify_teacher", "Male", None))
        self.genderComboBox.setItemText(1, _translate("modify_teacher", "Female", None))
        self.SSNLabel.setText(_translate("modify_teacher", "SSN*", None))
        self.payRateLabel.setText(_translate("modify_teacher", "Pay Rate", None))
        self.medicalLabel.setText(_translate("modify_teacher", "Medical Information", None))
        self.requiredLabel.setText(_translate("modify_teacher", "* Required Field", None))
        self.Submit_btn.setText(_translate("modify_teacher", "Submit", None))
        self.Select_teacher_btn.setText(_translate("modify_teacher", "Select", None))
        self.DOBlabel.setText(_translate("modify_teacher", "Date of Birth*", None))
        self.zipcodeLabel.setText(_translate("modify_teacher", "Zipcode", None))

