# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Update_Teacher.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class modify_teacher(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(698, 518)
        self.formLayoutWidget = QtGui.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 681, 501))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.enterName = QtGui.QLabel(self.formLayoutWidget)
        self.enterName.setObjectName(_fromUtf8("enterName"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.enterName)
        self.nameLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nameLineEdit)
        self.homePhone = QtGui.QLabel(self.formLayoutWidget)
        self.homePhone.setObjectName(_fromUtf8("homePhone"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.homePhone)
        self.homePhoneLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.homePhoneLineEdit.setObjectName(_fromUtf8("homePhoneLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.homePhoneLineEdit)
        self.cellPhone = QtGui.QLabel(self.formLayoutWidget)
        self.cellPhone.setObjectName(_fromUtf8("cellPhone"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.cellPhone)
        self.cellPhoneLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.cellPhoneLineEdit.setObjectName(_fromUtf8("cellPhoneLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cellPhoneLineEdit)
        self.workPhone = QtGui.QLabel(self.formLayoutWidget)
        self.workPhone.setObjectName(_fromUtf8("workPhone"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.workPhone)
        self.workPhoneLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.workPhoneLineEdit.setObjectName(_fromUtf8("workPhoneLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.workPhoneLineEdit)
        self.address = QtGui.QLabel(self.formLayoutWidget)
        self.address.setObjectName(_fromUtf8("adress"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.address)
        self.addressLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.addressLineEdit.setObjectName(_fromUtf8("adressLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.addressLineEdit)
        self.cityLabel = QtGui.QLabel(self.formLayoutWidget)
        self.cityLabel.setObjectName(_fromUtf8("cityLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.cityLabel)
        self.cityLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.cityLineEdit.setObjectName(_fromUtf8("cityLineEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.cityLineEdit)
        self.stateLabel = QtGui.QLabel(self.formLayoutWidget)
        self.stateLabel.setObjectName(_fromUtf8("stateLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.stateLabel)
        self.stateComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.stateComboBox.setObjectName(_fromUtf8("stateComboBox"))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.stateComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.stateComboBox)
        self.email = QtGui.QLabel(self.formLayoutWidget)
        self.email.setObjectName(_fromUtf8("email"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.email)
        self.emailLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.emailLineEdit.setObjectName(_fromUtf8("emailLineEdit"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.emailLineEdit)
        self.genderLabel = QtGui.QLabel(self.formLayoutWidget)
        self.genderLabel.setObjectName(_fromUtf8("genderLabel"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.genderLabel)
        self.genderComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.genderComboBox.setObjectName(_fromUtf8("genderComboBox"))
        self.genderComboBox.addItem(_fromUtf8(""))
        self.genderComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.genderComboBox)
        self.SSNLabel = QtGui.QLabel(self.formLayoutWidget)
        self.SSNLabel.setObjectName(_fromUtf8("SSNLabel"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.SSNLabel)
        self.SSNLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.SSNLineEdit.setObjectName(_fromUtf8("sSNLineEdit"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.SSNLineEdit)
        self.payRateLabel = QtGui.QLabel(self.formLayoutWidget)
        self.payRateLabel.setObjectName(_fromUtf8("payRateLabel"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.payRateLabel)
        self.payRateDoubleSpinBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.payRateDoubleSpinBox.setSingleStep(0.01)
        self.payRateDoubleSpinBox.setObjectName(_fromUtf8("payRateDoubleSpinBox"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.payRateDoubleSpinBox)
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label)
        self.textEdit = QtGui.QTextEdit(self.formLayoutWidget)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.textEdit)
        self.pushButton = QtGui.QPushButton(self.formLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.pushButton)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.enterName.setText(_translate("Dialog", "Name*", None))
        self.homePhone.setText(_translate("Dialog", "Home Phone*", None))
        self.cellPhone.setText(_translate("Dialog", "Cell Phone", None))
        self.workPhone.setText(_translate("Dialog", "Work Phone", None))
        self.address.setText(_translate("Dialog", "Address*", None))
        self.cityLabel.setText(_translate("Dialog", "City*", None))
        self.stateLabel.setText(_translate("Dialog", "State*", None))
        self.stateComboBox.setItemText(0, _translate("Dialog", "Alabama", None))
        self.stateComboBox.setItemText(1, _translate("Dialog", "Alaska", None))
        self.stateComboBox.setItemText(2, _translate("Dialog", "Arizona", None))
        self.stateComboBox.setItemText(3, _translate("Dialog", "Arkansas", None))
        self.stateComboBox.setItemText(4, _translate("Dialog", "California", None))
        self.stateComboBox.setItemText(5, _translate("Dialog", "Colorado", None))
        self.stateComboBox.setItemText(6, _translate("Dialog", "Connecticut", None))
        self.stateComboBox.setItemText(7, _translate("Dialog", "Delaware", None))
        self.stateComboBox.setItemText(8, _translate("Dialog", "Florida", None))
        self.stateComboBox.setItemText(9, _translate("Dialog", "Georgia", None))
        self.stateComboBox.setItemText(10, _translate("Dialog", "Hawaii", None))
        self.stateComboBox.setItemText(11, _translate("Dialog", "Idaho", None))
        self.stateComboBox.setItemText(12, _translate("Dialog", "Illinois", None))
        self.stateComboBox.setItemText(13, _translate("Dialog", "Indiana", None))
        self.stateComboBox.setItemText(14, _translate("Dialog", "Iowa", None))
        self.stateComboBox.setItemText(15, _translate("Dialog", "Kansas", None))
        self.stateComboBox.setItemText(16, _translate("Dialog", "Kentucky", None))
        self.stateComboBox.setItemText(17, _translate("Dialog", "Louisiana", None))
        self.stateComboBox.setItemText(18, _translate("Dialog", "Maine", None))
        self.stateComboBox.setItemText(19, _translate("Dialog", "Maryland", None))
        self.stateComboBox.setItemText(20, _translate("Dialog", "Massachusetts", None))
        self.stateComboBox.setItemText(21, _translate("Dialog", "Michigan", None))
        self.stateComboBox.setItemText(22, _translate("Dialog", "Minnesota", None))
        self.stateComboBox.setItemText(23, _translate("Dialog", "Mississippi", None))
        self.stateComboBox.setItemText(24, _translate("Dialog", "Missouri", None))
        self.stateComboBox.setItemText(25, _translate("Dialog", "Montana", None))
        self.stateComboBox.setItemText(26, _translate("Dialog", "Nebraska", None))
        self.stateComboBox.setItemText(27, _translate("Dialog", "Nevada", None))
        self.stateComboBox.setItemText(28, _translate("Dialog", "New Hampshire", None))
        self.stateComboBox.setItemText(29, _translate("Dialog", "New Jersey", None))
        self.stateComboBox.setItemText(30, _translate("Dialog", "New Mexico", None))
        self.stateComboBox.setItemText(31, _translate("Dialog", "New York", None))
        self.stateComboBox.setItemText(32, _translate("Dialog", "North Carolina", None))
        self.stateComboBox.setItemText(33, _translate("Dialog", "North Dakota", None))
        self.stateComboBox.setItemText(34, _translate("Dialog", "Ohio", None))
        self.stateComboBox.setItemText(35, _translate("Dialog", "Oklahoma", None))
        self.stateComboBox.setItemText(36, _translate("Dialog", "Oregon", None))
        self.stateComboBox.setItemText(37, _translate("Dialog", "Pennsylvania", None))
        self.stateComboBox.setItemText(38, _translate("Dialog", "Rhode Island", None))
        self.stateComboBox.setItemText(39, _translate("Dialog", "South Carolina", None))
        self.stateComboBox.setItemText(40, _translate("Dialog", "South Dakota", None))
        self.stateComboBox.setItemText(41, _translate("Dialog", "Tennessee", None))
        self.stateComboBox.setItemText(42, _translate("Dialog", "Texas", None))
        self.stateComboBox.setItemText(43, _translate("Dialog", "Utah", None))
        self.stateComboBox.setItemText(44, _translate("Dialog", "Vermont", None))
        self.stateComboBox.setItemText(45, _translate("Dialog", "Virginia", None))
        self.stateComboBox.setItemText(46, _translate("Dialog", "Washington", None))
        self.stateComboBox.setItemText(47, _translate("Dialog", "West Virginia", None))
        self.stateComboBox.setItemText(48, _translate("Dialog", "Wisconsin", None))
        self.stateComboBox.setItemText(49, _translate("Dialog", "Wyoming", None))
        self.email.setText(_translate("Dialog", "Email", None))
        self.genderLabel.setText(_translate("Dialog", "Gender", None))
        self.genderComboBox.setItemText(0, _translate("Dialog", "Male", None))
        self.genderComboBox.setItemText(1, _translate("Dialog", "Female", None))
        self.SSNLabel.setText(_translate("Dialog", "SSN*", None))
        self.payRateLabel.setText(_translate("Dialog", "Pay Rate", None))
        self.label.setText(_translate("Dialog", "Medical Information", None))
        self.pushButton.setText(_translate("Dialog", "Submit", None))
        self.label_2.setText(_translate("Dialog", "* Required Field", None))

