# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin Landing.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Admin_Landing(object):
    def setupUi(self, Admin_Landing):
        Admin_Landing.setObjectName(_fromUtf8("Admin_Landing"))
        Admin_Landing.resize(573, 358)
        self.centralwidget = QtGui.QWidget(Admin_Landing)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 0, 551, 321))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.Landing = QtGui.QWidget()
        self.Landing.setObjectName(_fromUtf8("Landing"))
        self.verticalLayoutWidget = QtGui.QWidget(self.Landing)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 521, 311))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.Employee_btn = QtGui.QPushButton(self.groupBox)
        self.Employee_btn.setGeometry(QtCore.QRect(60, 30, 261, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Employee_btn.setFont(font)
        self.Employee_btn.setObjectName(_fromUtf8("Employee_btn"))
        self.Quit_btn = QtGui.QPushButton(self.groupBox)
        self.Quit_btn.setGeometry(QtCore.QRect(410, 270, 75, 23))
        self.Quit_btn.setObjectName(_fromUtf8("Quit_btn"))
        self.Logout_btn = QtGui.QPushButton(self.groupBox)
        self.Logout_btn.setGeometry(QtCore.QRect(320, 270, 75, 23))
        self.Logout_btn.setObjectName(_fromUtf8("Logout_btn"))
        self.Billing_btn = QtGui.QPushButton(self.groupBox)
        self.Billing_btn.setGeometry(QtCore.QRect(60, 210, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.Billing_btn.setFont(font)
        self.Billing_btn.setObjectName(_fromUtf8("Billing_btn"))
        self.Student_btn = QtGui.QPushButton(self.groupBox)
        self.Student_btn.setGeometry(QtCore.QRect(60, 150, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.Student_btn.setFont(font)
        self.Student_btn.setObjectName(_fromUtf8("Student_btn"))
        self.Class_btn = QtGui.QPushButton(self.groupBox)
        self.Class_btn.setGeometry(QtCore.QRect(60, 90, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.Class_btn.setFont(font)
        self.Class_btn.setObjectName(_fromUtf8("Class_btn"))
        self.verticalLayout.addWidget(self.groupBox)
        self.stackedWidget.addWidget(self.Landing)
        self.Admin_employee = QtGui.QWidget()
        self.Admin_employee.setObjectName(_fromUtf8("Admin_employee"))
        self.Employee_back_btn = QtGui.QPushButton(self.Admin_employee)
        self.Employee_back_btn.setGeometry(QtCore.QRect(350, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.Employee_back_btn.setFont(font)
        self.Employee_back_btn.setObjectName(_fromUtf8("Employee_back_btn"))
        self.New_teacher_btn = QtGui.QPushButton(self.Admin_employee)
        self.New_teacher_btn.setGeometry(QtCore.QRect(110, 210, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.New_teacher_btn.setFont(font)
        self.New_teacher_btn.setObjectName(_fromUtf8("New_teacher_btn"))
        self.Search_teacher_btn = QtGui.QPushButton(self.Admin_employee)
        self.Search_teacher_btn.setGeometry(QtCore.QRect(110, 30, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Search_teacher_btn.setFont(font)
        self.Search_teacher_btn.setObjectName(_fromUtf8("Search_teacher_btn"))
        self.Update_teacher_btn = QtGui.QPushButton(self.Admin_employee)
        self.Update_teacher_btn.setGeometry(QtCore.QRect(110, 90, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Update_teacher_btn.setFont(font)
        self.Update_teacher_btn.setObjectName(_fromUtf8("Update_teacher_btn"))
        self.Assign_teacher_btn = QtGui.QPushButton(self.Admin_employee)
        self.Assign_teacher_btn.setGeometry(QtCore.QRect(110, 150, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Assign_teacher_btn.setFont(font)
        self.Assign_teacher_btn.setObjectName(_fromUtf8("Assign_teacher_btn"))
        self.Quit_btn_2 = QtGui.QPushButton(self.Admin_employee)
        self.Quit_btn_2.setGeometry(QtCore.QRect(430, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.Quit_btn_2.setFont(font)
        self.Quit_btn_2.setObjectName(_fromUtf8("Quit_btn_2"))
        self.stackedWidget.addWidget(self.Admin_employee)
        self.Admin_class = QtGui.QWidget()
        self.Admin_class.setObjectName(_fromUtf8("Admin_class"))
        self.Class_tuition_btn = QtGui.QPushButton(self.Admin_class)
        self.Class_tuition_btn.setGeometry(QtCore.QRect(120, 210, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Class_tuition_btn.setFont(font)
        self.Class_tuition_btn.setObjectName(_fromUtf8("Class_tuition_btn"))
        self.View_class_btn = QtGui.QPushButton(self.Admin_class)
        self.View_class_btn.setGeometry(QtCore.QRect(120, 30, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.View_class_btn.setFont(font)
        self.View_class_btn.setObjectName(_fromUtf8("View_class_btn"))
        self.Add_Class_btn = QtGui.QPushButton(self.Admin_class)
        self.Add_Class_btn.setGeometry(QtCore.QRect(120, 150, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Add_Class_btn.setFont(font)
        self.Add_Class_btn.setObjectName(_fromUtf8("Add_Class_btn"))
        self.Quit_btn_3 = QtGui.QPushButton(self.Admin_class)
        self.Quit_btn_3.setGeometry(QtCore.QRect(440, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.Quit_btn_3.setFont(font)
        self.Quit_btn_3.setObjectName(_fromUtf8("Quit_btn_3"))
        self.Class_back_btn = QtGui.QPushButton(self.Admin_class)
        self.Class_back_btn.setGeometry(QtCore.QRect(360, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.Class_back_btn.setFont(font)
        self.Class_back_btn.setObjectName(_fromUtf8("Class_back_btn"))
        self.Modify_class_btn = QtGui.QPushButton(self.Admin_class)
        self.Modify_class_btn.setGeometry(QtCore.QRect(120, 90, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Modify_class_btn.setFont(font)
        self.Modify_class_btn.setObjectName(_fromUtf8("Modify_class_btn"))
        self.stackedWidget.addWidget(self.Admin_class)
        self.Admin_Student = QtGui.QWidget()
        self.Admin_Student.setObjectName(_fromUtf8("Admin_Student"))
        self.Registration_btn = QtGui.QPushButton(self.Admin_Student)
        self.Registration_btn.setGeometry(QtCore.QRect(110, 210, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Registration_btn.setFont(font)
        self.Registration_btn.setObjectName(_fromUtf8("Registration_btn"))
        self.Search_student_btn = QtGui.QPushButton(self.Admin_Student)
        self.Search_student_btn.setGeometry(QtCore.QRect(110, 30, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Search_student_btn.setFont(font)
        self.Search_student_btn.setObjectName(_fromUtf8("Search_student_btn"))
        self.Add_student_btn = QtGui.QPushButton(self.Admin_Student)
        self.Add_student_btn.setGeometry(QtCore.QRect(110, 150, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Add_student_btn.setFont(font)
        self.Add_student_btn.setObjectName(_fromUtf8("Add_student_btn"))
        self.Quit_btn_4 = QtGui.QPushButton(self.Admin_Student)
        self.Quit_btn_4.setGeometry(QtCore.QRect(430, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.Quit_btn_4.setFont(font)
        self.Quit_btn_4.setObjectName(_fromUtf8("Quit_btn_4"))
        self.Student_back_btn = QtGui.QPushButton(self.Admin_Student)
        self.Student_back_btn.setGeometry(QtCore.QRect(350, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.Student_back_btn.setFont(font)
        self.Student_back_btn.setObjectName(_fromUtf8("Student_back_btn"))
        self.Modify_student_btn = QtGui.QPushButton(self.Admin_Student)
        self.Modify_student_btn.setGeometry(QtCore.QRect(110, 90, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Modify_student_btn.setFont(font)
        self.Modify_student_btn.setObjectName(_fromUtf8("Modify_student_btn"))
        self.stackedWidget.addWidget(self.Admin_Student)
        self.Admin_Payroll = QtGui.QWidget()
        self.Admin_Payroll.setObjectName(_fromUtf8("Admin_Payroll"))
        self.Family_billing_btn = QtGui.QPushButton(self.Admin_Payroll)
        self.Family_billing_btn.setGeometry(QtCore.QRect(120, 150, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Family_billing_btn.setFont(font)
        self.Family_billing_btn.setObjectName(_fromUtf8("Family_billing_btn"))
        self.Quit_btn_5 = QtGui.QPushButton(self.Admin_Payroll)
        self.Quit_btn_5.setGeometry(QtCore.QRect(440, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.Quit_btn_5.setFont(font)
        self.Quit_btn_5.setObjectName(_fromUtf8("Quit_btn_5"))
        self.Hours_btn = QtGui.QPushButton(self.Admin_Payroll)
        self.Hours_btn.setGeometry(QtCore.QRect(120, 90, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Hours_btn.setFont(font)
        self.Hours_btn.setObjectName(_fromUtf8("Hours_btn"))
        self.Payroll_back_btn = QtGui.QPushButton(self.Admin_Payroll)
        self.Payroll_back_btn.setGeometry(QtCore.QRect(360, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.Payroll_back_btn.setFont(font)
        self.Payroll_back_btn.setObjectName(_fromUtf8("Payroll_back_btn"))
        self.Payroll_btn = QtGui.QPushButton(self.Admin_Payroll)
        self.Payroll_btn.setGeometry(QtCore.QRect(120, 30, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Payroll_btn.setFont(font)
        self.Payroll_btn.setObjectName(_fromUtf8("Payroll_btn"))
        self.stackedWidget.addWidget(self.Admin_Payroll)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.Teacher_search_back_btn = QtGui.QPushButton(self.page)
        self.Teacher_search_back_btn.setGeometry(QtCore.QRect(460, 290, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.Teacher_search_back_btn.setFont(font)
        self.Teacher_search_back_btn.setObjectName(_fromUtf8("Teacher_search_back_btn"))
        self.Search_lineEdit = QtGui.QLineEdit(self.page)
        self.Search_lineEdit.setGeometry(QtCore.QRect(100, 10, 221, 21))
        self.Search_lineEdit.setObjectName(_fromUtf8("Search_lineEdit"))
        self.Teacher_view = QtGui.QTableView(self.page)
        self.Teacher_view.setGeometry(QtCore.QRect(0, 40, 541, 241))
        self.Teacher_view.setObjectName(_fromUtf8("Teacher_view"))
        self.label = QtGui.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(0, 10, 121, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.Search_btn = QtGui.QPushButton(self.page)
        self.Search_btn.setGeometry(QtCore.QRect(330, 10, 101, 23))
        self.Search_btn.setObjectName(_fromUtf8("Search_btn"))
        self.Adv_search_btn = QtGui.QPushButton(self.page)
        self.Adv_search_btn.setGeometry(QtCore.QRect(440, 10, 101, 23))
        self.Adv_search_btn.setObjectName(_fromUtf8("Adv_search_btn"))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.pushButton = QtGui.QPushButton(self.page_2)
        self.pushButton.setGeometry(QtCore.QRect(360, 280, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.page_2)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 280, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.comboBox = QtGui.QComboBox(self.page_2)
        self.comboBox.setGeometry(QtCore.QRect(20, 50, 211, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.label_2 = QtGui.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 71, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comboBox_2 = QtGui.QComboBox(self.page_3)
        self.comboBox_2.setGeometry(QtCore.QRect(100, 60, 241, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.label_3 = QtGui.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 71, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.comboBox_3 = QtGui.QComboBox(self.page_3)
        self.comboBox_3.setGeometry(QtCore.QRect(100, 120, 241, 22))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.pushButton_3 = QtGui.QPushButton(self.page_3)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 180, 201, 21))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.page_3)
        self.pushButton_4.setGeometry(QtCore.QRect(430, 280, 75, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.pushButton_5 = QtGui.QPushButton(self.page_4)
        self.pushButton_5.setGeometry(QtCore.QRect(360, 280, 75, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(self.page_4)
        self.pushButton_6.setGeometry(QtCore.QRect(440, 280, 75, 23))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.scrollArea = QtGui.QScrollArea(self.page_4)
        self.scrollArea.setGeometry(QtCore.QRect(9, 9, 511, 261))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 509, 259))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 46, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(10, 190, 46, 13))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_2 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 10, 391, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_7 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_7.setGeometry(QtCore.QRect(60, 160, 391, 20))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_3 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_3.setGeometry(QtCore.QRect(60, 40, 391, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(10, 100, 46, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(10, 160, 46, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_8 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_8.setGeometry(QtCore.QRect(60, 190, 391, 20))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 46, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(10, 130, 46, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_5 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_5.setGeometry(QtCore.QRect(60, 100, 391, 20))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_4 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_4.setGeometry(QtCore.QRect(60, 70, 391, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_6 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_6.setGeometry(QtCore.QRect(60, 130, 391, 20))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(10, 220, 46, 13))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_9 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_9.setGeometry(QtCore.QRect(60, 220, 391, 20))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.page_4)
        Admin_Landing.setCentralWidget(self.centralwidget)
        self.Admin_menubar = QtGui.QMenuBar(Admin_Landing)
        self.Admin_menubar.setGeometry(QtCore.QRect(0, 0, 573, 21))
        self.Admin_menubar.setObjectName(_fromUtf8("Admin_menubar"))
        self.menuNavigation = QtGui.QMenu(self.Admin_menubar)
        self.menuNavigation.setObjectName(_fromUtf8("menuNavigation"))
        Admin_Landing.setMenuBar(self.Admin_menubar)
        self.Admin_menubar.addAction(self.menuNavigation.menuAction())

        self.retranslateUi(Admin_Landing)
        QtCore.QMetaObject.connectSlotsByName(Admin_Landing)

    def retranslateUi(self, Admin_Landing):
        Admin_Landing.setWindowTitle(_translate("Admin_Landing", "Admin Landing", None))
        self.groupBox.setTitle(_translate("Admin_Landing", "Admin", None))
        self.Employee_btn.setText(_translate("Admin_Landing", "Manage Employees", None))
        self.Quit_btn.setText(_translate("Admin_Landing", "Quit", None))
        self.Logout_btn.setText(_translate("Admin_Landing", "Logout", None))
        self.Billing_btn.setText(_translate("Admin_Landing", "Manage Billing and Payroll", None))
        self.Student_btn.setText(_translate("Admin_Landing", "Manage Students", None))
        self.Class_btn.setText(_translate("Admin_Landing", "Manage Classes", None))
        self.Employee_back_btn.setText(_translate("Admin_Landing", "Back", None))
        self.New_teacher_btn.setText(_translate("Admin_Landing", "Enter New Teacher", None))
        self.Search_teacher_btn.setText(_translate("Admin_Landing", "Search For Teacher", None))
        self.Update_teacher_btn.setText(_translate("Admin_Landing", "Update Teacher Information", None))
        self.Assign_teacher_btn.setText(_translate("Admin_Landing", "Assign Teacher to Class", None))
        self.Quit_btn_2.setText(_translate("Admin_Landing", "Quit", None))
        self.Class_tuition_btn.setText(_translate("Admin_Landing", "Class Tuition", None))
        self.View_class_btn.setText(_translate("Admin_Landing", "View Class", None))
        self.Add_Class_btn.setText(_translate("Admin_Landing", "Add a Class", None))
        self.Quit_btn_3.setText(_translate("Admin_Landing", "Quit", None))
        self.Class_back_btn.setText(_translate("Admin_Landing", "Back", None))
        self.Modify_class_btn.setText(_translate("Admin_Landing", "Modify a Class", None))
        self.Registration_btn.setText(_translate("Admin_Landing", "Registration", None))
        self.Search_student_btn.setText(_translate("Admin_Landing", "Search For Students", None))
        self.Add_student_btn.setText(_translate("Admin_Landing", "Add/Remove Student", None))
        self.Quit_btn_4.setText(_translate("Admin_Landing", "Quit", None))
        self.Student_back_btn.setText(_translate("Admin_Landing", "Back", None))
        self.Modify_student_btn.setText(_translate("Admin_Landing", "Modify Student Information", None))
        self.Family_billing_btn.setText(_translate("Admin_Landing", "Family Billing", None))
        self.Quit_btn_5.setText(_translate("Admin_Landing", "Quit", None))
        self.Hours_btn.setText(_translate("Admin_Landing", "See Teacher Hours", None))
        self.Payroll_back_btn.setText(_translate("Admin_Landing", "Back", None))
        self.Payroll_btn.setText(_translate("Admin_Landing", "Payroll", None))
        self.Teacher_search_back_btn.setText(_translate("Admin_Landing", "Back", None))
        self.label.setText(_translate("Admin_Landing", "Enter Teacher Name", None))
        self.Search_btn.setText(_translate("Admin_Landing", "Search", None))
        self.Adv_search_btn.setText(_translate("Admin_Landing", "Advanced Search", None))
        self.pushButton.setText(_translate("Admin_Landing", "Submit", None))
        self.pushButton_2.setText(_translate("Admin_Landing", "Back", None))
        self.label_2.setText(_translate("Admin_Landing", "Select Class", None))
        self.label_3.setText(_translate("Admin_Landing", "Select Teacher", None))
        self.pushButton_3.setText(_translate("Admin_Landing", "Submit", None))
        self.pushButton_4.setText(_translate("Admin_Landing", "Back", None))
        self.pushButton_5.setText(_translate("Admin_Landing", "Submit", None))
        self.pushButton_6.setText(_translate("Admin_Landing", "Back", None))
        self.label_6.setText(_translate("Admin_Landing", "TextLabel", None))
        self.label_10.setText(_translate("Admin_Landing", "TextLabel", None))
        self.label_4.setText(_translate("Admin_Landing", "TextLabel", None))
        self.label_7.setText(_translate("Admin_Landing", "TextLabel", None))
        self.label_9.setText(_translate("Admin_Landing", "TextLabel", None))
        self.label_5.setText(_translate("Admin_Landing", "TextLabel", None))
        self.label_8.setText(_translate("Admin_Landing", "TextLabel", None))
        self.label_11.setText(_translate("Admin_Landing", "TextLabel", None))
        self.menuNavigation.setTitle(_translate("Admin_Landing", "Navigation", None))

